name: AleTrail
description: "Got a thirst? We got you"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon-128x128.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  animated_notch_bottom_bar: ^1.0.2
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.0.9
  geolocator: ^12.0.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  image_picker: ^1.1.1
  firebase_storage: ^12.1.0
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.0
  flutter_image_compress: ^2.3.0
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  image: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/svg/orangeCorner.svg
    - lib/assets/images/svg/yellowCorner.svg
    - lib/assets/images/svg/AleTrailtitle.svg
    - lib/assets/images/svg/GoogleIcon.svg
    - lib/assets/images/svg/InstaLogo.svg
    - lib/assets/images/svg/TwitterIcon.svg
    - lib/assets/images/svg/TopRightOrange.svg
    - lib/assets/images/svg/AleTrailNewVenue.svg
    - lib/assets/images/svg/AleTrailNewMenu.svg
    - lib/assets/images/svg/AletrailNewProduct.svg
    - lib/assets/images/svg/AletrailMenus.svg
    - lib/assets/images/png/PriceMarker.png
    - lib/assets/icons/icon-128x128.png

  fonts:
    - family: TrainOne
      fonts:
        - asset: lib/assets/fonts/TrainOne-Regular.ttf
          style: normal
