class Products {
  List<String> productTypes = [
    "Soft Drink",
    "Beer",
    "Ale",
    "Craft Beer",
    "Cider",
    "Dry Cider",
    "Spirits",
    "Wine",
    "Cocktail",
    "Mocktail",
    "Lager",
    "Pilsner",
    "Stout",
    "Porter",
    "Mead",
    "Whiskey",
    "Vodka",
    "Rum",
    "Gin",
    "Tequila",
    "Brandy",
    "Schnapps",
    "Liqueur",
    "Non-Alcoholic Beer",
    "Non-Alcoholic Wine",
    "Juice",
    "Mineral Water",
    "Tonic Water",
    "Energy Drink",
    "Hot Chocolate",
    "Tea",
    "Coffee",
    "Espresso",
    "Latte",
    "Cappuccino",
    "Americano",
    "Irish Coffee"
  ];
}
